### ISSUE TITLE
about the grad of sdf model

### ISSUE THREAD

**Issue by s1752729916** [Tencent/BlockFusion#6]
hi,
thanks for your great work. 
Is it convenient for you to share the code for calculating the SDF gradient? I have implemented the Eq.6 for calculating gradients in your article, but the results are always incorrect

**Comment by rabbityl** [comment]
check https://github.com/Tencent/BlockFusion/blob/main/fit_triplane/fit.py#L393-L402

**Comment by s1752729916** [comment]
thanks for your reply!
